format:
  line_width: 120
  tab_size: 2
  use_tabchars: false
  separate_ctrl_name_with_space: true
  separate_fn_name_with_space: false
  dangle_parens: true
  dangle_align: prefix
  min_prefix_chars: 4
  max_prefix_chars: 10
  max_lines_hwrap: 2
  command_case: lowercase
  keyword_case: unchanged
  always_wrap: []

markup:
  enable_markup: false

lint:
  disabled_codes:
    - C0103  # Variable naming - we use UPPERCASE
    - C0111  # Module docstring - we use RST bracket comments instead
    - C0112  # Function docstring - we use RST bracket comments instead
    - C0113  # Missing COMMENT - optional argument
    - C0301  # Line too long - we allow 120
    - C0307  # Indentation style - we use our own style
    - E1120  # Missing argument - false positive for newer CMake
    - E1126  # Invalid form discriminator - false positive for newer CMake
