#!/bin/bash
#
# Generic bash completion installer for args-based executables
#
# Usage:
#   spsArgsCompletion.bash <executable-path> [symlink-path]
#
# Installs completion to:
#   ~/.local/share/bash-completion/completions/<executable-name>
#

set -e

PROG_PATH="$1"
SYMLINK_PATH="${2:-}"

if [[ -z "$PROG_PATH" ]]; then
    echo "Usage: $0 <executable-path> [symlink-path]"
    exit 1
fi

# Resolve paths
if [[ -f "$PROG_PATH" ]]; then
    PROG_PATH="$(readlink -f "$PROG_PATH")"
elif command -v "$PROG_PATH" &> /dev/null; then
    PROG_PATH="$(command -v "$PROG_PATH")"
else
    echo "Error: Cannot find executable '$PROG_PATH'"
    exit 1
fi

PROG_NAME="$(basename "$PROG_PATH")"

# Resolve symlink path if provided
if [[ -n "$SYMLINK_PATH" && -f "$SYMLINK_PATH" ]]; then
    SYMLINK_PATH="$(cd "$(dirname "$SYMLINK_PATH")" && pwd)/$(basename "$SYMLINK_PATH")"
fi

# Create completion directory
COMPLETION_DIR="$HOME/.local/share/bash-completion/completions"
mkdir -p "$COMPLETION_DIR"
COMPLETION_FILE="$COMPLETION_DIR/$PROG_NAME"

# Generate completion script
cat > "$COMPLETION_FILE" << EOF
# Bash completion for $PROG_NAME
# Generated by spsArgsCompletion.bash

_${PROG_NAME}_completions()
{
    local cur="\${COMP_WORDS[COMP_CWORD]}"

    # Use the program's built-in completion
    local completions
    completions=\$("$PROG_PATH" --complete bash "\$COMP_CWORD" "\${COMP_WORDS[@]}" 2>/dev/null)

    if [[ -n "\$completions" ]]; then
        COMPREPLY=( \$(compgen -W "\$completions" -- "\$cur") )
    fi

    # Directory completion for common path arguments
    local prev="\${COMP_WORDS[COMP_CWORD-1]}"
    case "\$prev" in
        -g|--grid-folder|*-dir|*-directory|*-path|*-folder)
            COMPREPLY+=( \$(compgen -d -- "\$cur") )
            ;;
    esac
}

# Register completion
complete -F _${PROG_NAME}_completions $PROG_NAME
complete -F _${PROG_NAME}_completions "$PROG_PATH"
EOF

# Add symlink registration if provided and different
if [[ -n "$SYMLINK_PATH" && "$SYMLINK_PATH" != "$PROG_PATH" ]]; then
    echo "complete -F _${PROG_NAME}_completions \"$SYMLINK_PATH\"" >> "$COMPLETION_FILE"
fi

echo "Bash completion installed: $COMPLETION_FILE"
