<#
.SYNOPSIS
    Generic PowerShell completion installer for args-based executables

.DESCRIPTION
    Generates and installs a PowerShell completion script for executables
    that use the Taywee/args library with --complete flag support.

.PARAMETER ExecutablePath
    Path to the executable

.PARAMETER CompletionDir
    Directory to install completion script (default: Documents/PowerShell/Completions)

.EXAMPLE
    .\spsArgsCompletion.ps1 -ExecutablePath "C:\path\to\myapp.exe"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ExecutablePath,

    [Parameter(Mandatory=$false)]
    [string]$CompletionDir = "$env:USERPROFILE\Documents\PowerShell\Completions"
)

# Verify executable exists
if (-not (Test-Path $ExecutablePath)) {
    Write-Error "Executable not found: $ExecutablePath"
    exit 1
}

$ExecutablePath = (Resolve-Path $ExecutablePath).Path
$ProgName = [System.IO.Path]::GetFileNameWithoutExtension($ExecutablePath)

# Create completion directory
if (-not (Test-Path $CompletionDir)) {
    New-Item -ItemType Directory -Path $CompletionDir -Force | Out-Null
}

$CompletionFile = Join-Path $CompletionDir "$ProgName.ps1"

# Generate completion script
$CompletionScript = @"
# PowerShell completion for $ProgName
# Generated by spsArgsCompletion.ps1
#
# To use, add to your PowerShell profile (`$PROFILE):
#   . "$CompletionFile"

Register-ArgumentCompleter -Native -CommandName '$ProgName' -ScriptBlock {
    param(`$wordToComplete, `$commandAst, `$cursorPosition)

    `$commandLine = `$commandAst.ToString()
    `$elements = `$commandLine -split '\s+'

    # Call the program's built-in completion
    `$completions = & '$ExecutablePath' --complete bash `$elements.Count @elements 2>`$null

    if (`$completions) {
        `$completions -split "``n" | Where-Object { `$_ -like "`$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new(
                `$_,
                `$_,
                'ParameterValue',
                `$_
            )
        }
    }
}
"@

Set-Content -Path $CompletionFile -Value $CompletionScript -Encoding UTF8

Write-Host "PowerShell completion installed: $CompletionFile"
Write-Host ""
Write-Host "To activate, add to your PowerShell profile:"
Write-Host "  . `"$CompletionFile`""
Write-Host ""
Write-Host "Or run now:"
Write-Host "  . `"$CompletionFile`""
