# compile_commands.json is only generated by Ninja and Makefile generators
if(CMAKE_EXPORT_COMPILE_COMMANDS AND CMAKE_GENERATOR MATCHES "Ninja|Makefiles")
  add_custom_target(copy_compile_commands ALL
    COMMAND ${CMAKE_COMMAND}
            -DSRC="${CMAKE_BINARY_DIR}/compile_commands.json"
            -DDST="${CMAKE_SOURCE_DIR}/compile_commands.json"
            -P "${CMAKE_CURRENT_LIST_DIR}/spsCopyIfExists.cmake"
    COMMENT "Copying compile_commands.json to source directory"
    VERBATIM
  )
endif()
