#[==[.rst:
**********
spsDoxygen
**********

Provides a simple function to set up Doxygen documentation generation.

Usage::

    include(spsDoxygen)
    sps_setup_doxygen(
      TARGET doc                          # Custom target name
      INPUT_DIRS ${PROJECT_SOURCE_DIR}/GridSearch  # Directories to document
      OUTPUT_DIR ${PROJECT_BINARY_DIR}/doc         # Output directory
      PROJECT_NAME "GridSearch"           # Project name in docs
      PROJECT_BRIEF "Ray-grid intersection library"  # Brief description
    )

Then build documentation with: ``cmake --build build --target doc``

#]==]

#[==[
  sps_setup_doxygen - Configure Doxygen documentation generation

  Arguments:
    TARGET        - Name of the custom target (default: doc)
    INPUT_DIRS    - List of directories to document
    OUTPUT_DIR    - Output directory for generated docs
    PROJECT_NAME  - Project name shown in documentation
    PROJECT_BRIEF - Brief project description
    EXCLUDE_PATTERNS - Additional patterns to exclude (optional)
    IMAGE_PATH    - Directories containing images for markdown (optional)
    PREDEFINED    - Preprocessor macro definitions (optional)
    EXPAND_AS_DEFINED - Macros to expand (optional)
    USE_DOT       - Enable Graphviz DOT graphs (optional, default OFF)
#]==]
function(sps_setup_doxygen)
  cmake_parse_arguments(DOXY
    "USE_DOT"
    "TARGET;OUTPUT_DIR;PROJECT_NAME;PROJECT_BRIEF"
    "INPUT_DIRS;EXCLUDE_PATTERNS;EXAMPLE_PATH;IMAGE_PATH;PREDEFINED;EXPAND_AS_DEFINED"
    ${ARGN}
  )

  # Set defaults
  if(NOT DOXY_TARGET)
    set(DOXY_TARGET "doc")
  endif()

  if(NOT DOXY_OUTPUT_DIR)
    set(DOXY_OUTPUT_DIR "${PROJECT_BINARY_DIR}/doc")
  endif()

  if(NOT DOXY_PROJECT_NAME)
    set(DOXY_PROJECT_NAME "${PROJECT_NAME}")
  endif()

  if(NOT DOXY_PROJECT_BRIEF)
    set(DOXY_PROJECT_BRIEF "")
  endif()

  if(NOT DOXY_INPUT_DIRS)
    set(DOXY_INPUT_DIRS "${PROJECT_SOURCE_DIR}")
  endif()

  # Find Doxygen
  find_package(Doxygen QUIET)

  if(NOT DOXYGEN_FOUND)
    message(STATUS "Doxygen not found - documentation target disabled")
    return()
  endif()

  message(STATUS "Doxygen found: ${DOXYGEN_EXECUTABLE}")
  message(STATUS "Documentation target '${DOXY_TARGET}' available")

  # Convert list to space-separated string for Doxyfile
  string(REPLACE ";" " " DOXY_INPUT_STR "${DOXY_INPUT_DIRS}")

  # Build exclude patterns (always exclude external dependencies)
  set(DOXY_EXCLUDE_LIST
    "*/Eigen/*"
    "*/build/*"
    "*/cmake-build-*/*"
    "*/_deps/*"
  )
  if(DOXY_EXCLUDE_PATTERNS)
    list(APPEND DOXY_EXCLUDE_LIST ${DOXY_EXCLUDE_PATTERNS})
  endif()
  string(REPLACE ";" " " DOXY_EXCLUDE_STR "${DOXY_EXCLUDE_LIST}")

  # Handle PREDEFINED macros
  if(DOXY_PREDEFINED)
    string(REPLACE ";" " \\\n                         " DOXY_PREDEFINED_STR "${DOXY_PREDEFINED}")
  else()
    set(DOXY_PREDEFINED_STR "")
  endif()

  # Handle EXPAND_AS_DEFINED macros
  if(DOXY_EXPAND_AS_DEFINED)
    string(REPLACE ";" " \\\n                         " DOXY_EXPAND_AS_DEFINED_STR "${DOXY_EXPAND_AS_DEFINED}")
  else()
    set(DOXY_EXPAND_AS_DEFINED_STR "")
  endif()

  # Handle DOT settings
  if(DOXY_USE_DOT)
    find_program(DOT_EXECUTABLE dot)
    if(DOT_EXECUTABLE)
      set(DOXY_HAVE_DOT "YES")
    else()
      message(STATUS "Graphviz dot not found - disabling DOT graphs")
      set(DOXY_HAVE_DOT "NO")
    endif()
  else()
    set(DOXY_HAVE_DOT "NO")
  endif()

  # Create output directory
  file(MAKE_DIRECTORY "${DOXY_OUTPUT_DIR}")

  # Generate Doxyfile in build directory
  set(DOXYFILE_PATH "${PROJECT_BINARY_DIR}/Doxyfile")

  file(WRITE "${DOXYFILE_PATH}" "# Doxyfile generated by spsDoxygen.cmake
# Do not edit - regenerate with cmake

#---------------------------------------------------------------------------
# Project settings
#---------------------------------------------------------------------------
PROJECT_NAME           = \"${DOXY_PROJECT_NAME}\"
PROJECT_BRIEF          = \"${DOXY_PROJECT_BRIEF}\"
PROJECT_NUMBER         = ${PROJECT_VERSION}
OUTPUT_DIRECTORY       = ${DOXY_OUTPUT_DIR}
MARKDOWN_SUPPORT       = YES
#---------------------------------------------------------------------------
# Input settings
#---------------------------------------------------------------------------
INPUT                  = ${DOXY_INPUT_STR}
RECURSIVE              = YES
FILE_PATTERNS          = *.h *.hpp *.cpp *.c *.md *.py
EXCLUDE_PATTERNS       = ${DOXY_EXCLUDE_STR}
USE_MDFILE_AS_MAINPAGE = ${PROJECT_SOURCE_DIR}/README.md
EXAMPLE_PATH           = ${DOXY_EXAMPLE_PATH}
IMAGE_PATH             = ${DOXY_IMAGE_PATH}

#---------------------------------------------------------------------------
# Documentation scope
#---------------------------------------------------------------------------
EXTRACT_ALL            = NO
EXTRACT_PRIVATE        = NO
EXTRACT_STATIC         = YES
EXTRACT_LOCAL_CLASSES  = YES
HIDE_UNDOC_MEMBERS     = YES
HIDE_UNDOC_CLASSES     = YES
HIDE_IN_BODY_DOCS      = NO

#---------------------------------------------------------------------------
# Output settings - HTML only
#---------------------------------------------------------------------------
GENERATE_HTML          = YES
GENERATE_LATEX         = NO
GENERATE_RTF           = NO
GENERATE_XML           = NO
GENERATE_MAN           = NO

#---------------------------------------------------------------------------
# HTML settings
#---------------------------------------------------------------------------
HTML_OUTPUT            = html
GENERATE_TREEVIEW      = YES
TREEVIEW_WIDTH         = 280

#---------------------------------------------------------------------------
# Math formulas (MathJax for LaTeX rendering)
#---------------------------------------------------------------------------
USE_MATHJAX            = YES
MATHJAX_VERSION        = MathJax_3
MATHJAX_FORMAT         = HTML-CSS
MATHJAX_RELPATH        = https://cdn.jsdelivr.net/npm/mathjax@3

#---------------------------------------------------------------------------
# Source browsing
#---------------------------------------------------------------------------
SOURCE_BROWSER         = YES
INLINE_SOURCES         = NO
STRIP_CODE_COMMENTS    = YES
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES

#---------------------------------------------------------------------------
# Preprocessing
#---------------------------------------------------------------------------
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = NO
SEARCH_INCLUDES        = YES
PREDEFINED             = ${DOXY_PREDEFINED_STR}
EXPAND_AS_DEFINED      = ${DOXY_EXPAND_AS_DEFINED_STR}

#---------------------------------------------------------------------------
# Graph settings (requires Graphviz)
#---------------------------------------------------------------------------
HAVE_DOT               = ${DOXY_HAVE_DOT}
COLLABORATION_GRAPH    = ${DOXY_HAVE_DOT}
INCLUDE_GRAPH          = ${DOXY_HAVE_DOT}
INCLUDED_BY_GRAPH      = ${DOXY_HAVE_DOT}
CALL_GRAPH             = NO
CALLER_GRAPH           = NO

#---------------------------------------------------------------------------
# Warning settings
#---------------------------------------------------------------------------
QUIET                  = YES
WARNINGS               = YES
WARN_IF_UNDOCUMENTED   = NO
WARN_IF_DOC_ERROR      = YES
WARN_NO_PARAMDOC       = NO
")

  # Create custom target
  add_custom_command(
    OUTPUT "${DOXY_OUTPUT_DIR}/html/index.html"
    COMMAND ${DOXYGEN_EXECUTABLE} "${DOXYFILE_PATH}"
    DEPENDS "${DOXYFILE_PATH}"
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    COMMENT "Generating API documentation with Doxygen"
    VERBATIM
  )

  add_custom_target(${DOXY_TARGET}
    DEPENDS "${DOXY_OUTPUT_DIR}/html/index.html"
  )

  # Optional: Add install rule for documentation
  install(
    DIRECTORY "${DOXY_OUTPUT_DIR}/html"
    DESTINATION "${CMAKE_INSTALL_DOCDIR}"
    COMPONENT Documentation
    OPTIONAL
  )

endfunction()
